apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: duemoselund/techtrends:latest
        ports:
        - containerPort: {{ .Values.service.targetport}}
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.targetport }}
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.targetport }}
          initialDelaySeconds: 5
          periodSeconds: 10